# CDF Kafka MCP Server Configuration Example
# Copy this file to kafka_config.yaml and update with your values

kafka:
  # Kafka cluster configuration
  bootstrap_servers: "localhost:9092"
  client_id: "cdf-kafka-mcp-server"
  security_protocol: "PLAINTEXT"  # PLAINTEXT, SASL_PLAINTEXT, SASL_SSL, SSL
  timeout: 30

  # SASL configuration (if using SASL)
  sasl_mechanism: "PLAIN"  # PLAIN, SCRAM-SHA-256, SCRAM-SHA-512
  sasl_username: "kafka-user"
  sasl_password: "kafka-password"

  # TLS configuration (if using TLS)
  tls_enabled: false
  tls_ca_cert: "/path/to/ca-cert.pem"
  tls_cert: "/path/to/client-cert.pem"
  tls_key: "/path/to/client-key.pem"

# Apache Knox Gateway configuration
knox:
  # Knox Gateway URL (e.g., https://knox-gateway.example.com:8443)
  gateway: "https://knox-gateway.example.com:8443"
  
  # Authentication method - either token or username/password
  token: "your-oauth2-token-here"  # OAuth2 token for Knox authentication
  username: "knox-user"  # Username for Knox authentication
  password: "knox-password"  # Password for Knox authentication
  
  # SSL verification settings
  verify_ssl: true
  ca_bundle: "/path/to/knox-ca-bundle.pem"  # Path to CA bundle file for SSL verification
  
  # Knox service name for Kafka
  service: "kafka"
